apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-odno
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nrpt-tenant/rhtap-demo-app/hacbs-test-project-odno@sha256:24bffbe43015e9781e45e04d12b75361ecc325b700440606731e38f88c64a257
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
